### PR TITLE
Add parameter lists

### PR DESCRIPTION
**Pull request by zmughal**
Required since [Function::Parameters](https://p3rl.org/Function::Parameters#Incompatibilites-with-version-1-of-Function::Parameters) 2

### CODE REVIEW

**Comment by basiliscos** [comment]
Oh, thanks a lot! It is the some kind of phycology-related application for Academy of Sciences of Belarus. Here is a short video, to let you know what it is about: 

https://thumbsnap.com/czBksLPf

**Comment by zmughal** [comment]
Yeah, I was interested in both the code and what it was being applied towards. Very cool!

This is for vision research, correct? Looks useful for models of eye-tracking/gaze/attention.

**Comment by basiliscos** [comment]
I think psychologists try to guess "the leading motive" during rotation or "behavioral patterns" or "ambient attention" and things like that. There was plans to add eye-tracking and/or mind waves oscilloscope, but I think it was considered too complex. 

If you are interested I'll post you the video release notes for v0.27 (coming soon). There are also some papers, mostly in Russian, but if u are interested, I can ask whether there are papers in English.

**Comment by zmughal** [comment]
I am interested! Either Russian or English papers would be fine[*].

[*] I am working on a software project to help translate papers (e.g., using Google Translate or some local translation tool). That's not all it does, but I got tired of reading some mathematics papers while having a translation dictionary open. :-)

**Comment by basiliscos** [comment]
Unfortunately all used math is only in my head (there is no rocket-science); so the papers are mostly psy-related.

 Surely, I'll send you the list of paper and video presentation :+1:

**Comment by basiliscos** [comment]
Hey, @zmughal . Here are the articles https://ufile.io/29mw1vr7 . Some of them are in English. Let me know if you need something else :)

**Comment by zmughal** [comment]
Thank you! :-D

**Pull request merged**
